### ISSUE TITLE
Need explanation

### ISSUE THREAD

**Issue by CaptainDredge** [kaushal02/interview-coding-problems#9]
https://github.com/kaushal02/interview-coding-problems/blob/bb3f9d8479f71a8a16927108d731f763bf9ddf92/Find%20Number%20of%20pairs.cpp#L50

Hi here in the above referenced line why are you adding n/i directly. Imo it should be like this
`while(ncopy)
{
    ncopy/= i;
    ipower++;
}`
Because we've to count the power of prime factor rather than directly adding the valu obtained by just dividing as the formulae for No' of divisors = (p1+1)(p2 +2)....(pn+1) where p1,p2,...pn are power of prime factors.
Is it a bug or am I somewhere wrong?

**Comment by kaushal02** [comment]
You are skipping the explanation posted in the top. The line serves following purpose: Given a prime number `p` and a natural number `n`, the maximum integer value `k` such that p<sup>k</sup> divides `n!` is given by -

k = [n/p] + [n/p<sup>2</sup>] + [n/p<sup>3</sup>] + ... 

where [x] represents floor function.

**Comment by CaptainDredge** [comment]
Thanks! Actually I was mistaking that we are directly getting n! as input in n(which is pretty lame :P)
